Introduces overrides argument
itech-media/classgroup pull request #5
Opened 2021-09-23 17:18 UTC by angelmeraz

The introduction of the overrides parameter intends to provide an interface to replace key values in a component library where default values are already present.

2021-09-23 17:22 UTC, angelmeraz commented on index.js
> +                if (col === '') break;
This check ensures empty strings are not added to the output, otherwise this causes the introduction of an unwanted space if an empty string were to be present.

2021-09-24 08:47 UTC, andrewspode requested changes

2021-09-24 08:47 UTC, andrewspode commented on index.js
> +    if (!overrides && !Object.keys(overrides).length) return collection;
I think this should be || not &&.

2021-09-24 09:09 UTC, JackPriceBurns requested changes

2021-09-24 09:09 UTC, JackPriceBurns commented on index.js
> +    }
```suggestion
        }

        collection[key] = overrides[key];
    }
```

2021-09-24 10:48 UTC, angelmeraz commented on index.js
> +    }
this now done

2021-09-24 10:49 UTC, angelmeraz commented on index.js
> +    if (!overrides && !Object.keys(overrides).length) return collection;
this now done

2021-09-24 12:19 UTC, JackPriceBurns approved these changes

2021-09-24 12:45 UTC, merged